function [ Y ] = synchrotron1(ref, x )
%% Evaluates the synchrotron function 1 for a given energy over critical energy ratio
%%% -"ref" is the synchrotron data reference given by get_synchrotron.m
%%% -"x" is the imput ratio 
%%% [Y] is the value of the normalized synchrotron 1 function. 
%
%%% The synchrotron1 function generated by GSL is limited to x<15. 
%%% This has been taken into account by the Gamma_num function (see its description for more details on this).
%%% If needed to, one can add null points to be able to use the function on a larger interval without getting NAN results. 

synchro_val=exp(ref(:,3));
synchro_axis=ref(:,1);

% Synch1(0)=0 
synchro_axis(1)=0; 
synchro_val(1)=0; 

%% Uncomment to extend the interval of definition
% synchro_axis(5601:5800)=[750:50:10700];
% synchro_axis(5801:6000)=[11200:500:110700];
% synchro_val(5500:6000)=0;
%%
Y=interp1(synchro_axis(:),synchro_val(:), x);

end

